pasteapp/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from paste.views import *

urlpatterns = patterns('',
    url('^changelog/$', TemplateView.as_view(template_name='changelog.html'),
        name='changelog'),
    url('^logout/$', logout_view, name='logout'),
    url('^paste/$', AddSnippetView.as_view()),
    url('^syntax/$', SyntaxView.as_view()),
    url('^(?P<slug>[\w\d]+)/delete/$', DeleteSnippetView.as_view()),
    url('^(?P<a>[\w\d]+)\.\.\.?(?P<b>[\w\d]+)/?$', DiffView.as_view()),
    url('^$', IndexView.as_view()),
    url('^u/(?P<slug>[\w\d]+)/$', UserView.as_view()),
    url(r'^browserid/', include('django_browserid.urls')),
    # Examples:
    # url(r'^$', 'pasteapp.views.home', name='home'),
    # url(r'^pasteapp/', include('pasteapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url('^(?P<slug>[\w\d]+)/?$', SnippetView.as_view()),
)

paste/models.py
import datetime
import random

from django.db import models
from django.contrib.auth.models import User

class SnippetManager(models.Manager):
    def not_expired(self):
        return self.exclude(expires__lte=datetime.datetime.now())

    def expired(self):
        return self.filter(expires__lte=datetime.datetime.now())

    def recent(self, limit=5):
        return self.not_expired().order_by('-published')[:limit]

    def public(self):
        return self.not_expired().filter(private=False)

class Snippet(models.Model):
    title = models.CharField(max_length=255, blank=True)
    slug = models.CharField(max_length=32, blank=True)
    content = models.TextField()

    author = models.ForeignKey(User, null=True, blank=True)
    private = models.BooleanField(default=True)
    published = models.DateTimeField(blank=True)
    expires = models.DateTimeField(blank=True, null=True)
    parent = models.ForeignKey('Snippet', blank=True, null=True)

    objects = SnippetManager()

    def __unicode__(self):
        return self.title or self.slug

    def get_absolute_url(self):
        return '/' + self.slug

    def save(self, *args, **kwargs):
        if not self.pk:
            if not self.slug:
                self.generate_slug()

            self.published = datetime.datetime.now()

            if not self.author:
                # Anonymous pastes expire in 2 weeks
                self.expires = self.published + datetime.timedelta(weeks=2)
        super(Snippet, self).save(*args, **kwargs)

    def generate_slug(self, length=6):
        t = 'abcdefghijkmnopqrstuvwwxyzABCDEFGHIJKLOMNOPQRSTUVWXYZ1234567890'
        self.slug = ''.join([random.choice(t) for i in range(length)])

paste/forms.py
import datetime
from django import forms
from paste.models import Snippet

EXPIRE_CHOICES = (
    (600,        'In 10 minutes'),
    (3600,       'In one hour'),
    (3600*24,    'In one day'),
    (3600*24*7,  'In one week'),
    (3600*24*14, 'In two weeks'),
    (3600*24*30, 'In one month'),
)

EXPIRE_DEFAULT = 3600*24*14

LEXER_LIST = (
    ('g', 'Guess'),
    ('bash', 'Bash'),
    ('c', 'C'),
    ('cpp', 'C++'),
    ('css', 'CSS'),
    ('diff', 'Diff'),
    ('django', 'Django/Jinja'),
    ('html', 'HTML'),
    ('js', 'JavaScript'),
    ('md', 'Markdown (Rendered)'),
    ('objective-c', 'Objective-C'),
    ('php', 'PHP'),
    ('python', 'Python'),
    ('python3', 'Python 3'),
    ('rb', 'Ruby'),
    ('rst', 'Restructured Text'),
    ('rrst', 'Restructured Text (Rendered)'),
    ('sql', 'SQL'),
    ('text', 'Text only'),
    ('vim', 'VimL'),
)
LEXER_DEFAULT = 'g'

class SnippetForm(forms.ModelForm):
    expire_options = forms.ChoiceField(
        choices=EXPIRE_CHOICES,
        initial=EXPIRE_DEFAULT,
        label='Expires',
    )

    lexer = forms.ChoiceField(
        choices=LEXER_LIST,
        initial=LEXER_DEFAULT,
        label='Syntax',
    )

    content = forms.CharField(widget=forms.Textarea(attrs={
        'cols': 40,
        'rows': 15,
        'class': 'input-xxlarge'
    }))
    parent = forms.ModelChoiceField(widget=forms.widgets.HiddenInput(),
                                    queryset=Snippet.objects.all(),
                                    empty_label="(None)", required=False)

    class Meta:
        model = Snippet
        fields = ('title', 'content', 'private', 'parent',)

    def save(self, *args, **kwargs):
        # Add expire datestamp
        self.instance.expires = datetime.datetime.now() + \
            datetime.timedelta(seconds=int(self.cleaned_data['expire_options']))

        super(SnippetForm, self).save(*args, **kwargs)

        return self.instance

paste/views.py
import difflib
import datetime
import textwrap
import re

from pygments import highlight
from pygments.lexers import *
from pygments.lexers import get_all_lexers
from pygments.formatters import HtmlFormatter

try:
    from markdown import Markdown
except ImportError:
    Markdown = False

try:
    from docutils.core import publish_parts
except ImportError:
    publish_parts = False

from django.utils.decorators import method_decorator
from django.utils.safestring import mark_safe
from django.utils.html import escape
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import TemplateView, DetailView, CreateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
from django.contrib.auth import logout

from paste.models import Snippet
from paste.forms import SnippetForm

from apikeys.models import Key

PASTE_KEY = 'paste'
VIM_MODELINE_RE = re.compile(r'(vi|vim)\: (set )?(.+)\:?')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def get_lexer(request, exclude=None):
    keys = request.GET.keys()

    if exclude:
        for x in exclude:
            if x in keys:
                keys.remove(x)

    if len(keys):
        return keys[0].lower()

    return None


class UserView(DetailView):
    model = User
    slug_field = 'username'
    template_name = 'paste/user_detail.html'

class SyntaxView(TemplateView):
    template_name = 'paste/syntax_list.html'

    def get_context_data(self, **kwargs):
        context = super(SyntaxView, self).get_context_data(**kwargs)
        context['syntax_list'] = sorted(
            [(i[1][0], i[0]) for i in get_all_lexers()] +
            [('rrst', 'Restructured Text (Rendered)'),
             ('md', 'Markdown (Rendered)')])
        return context

class DeleteSnippetView(DeleteView):
    success_url = '/'
    model = Snippet

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        return HttpResponseRedirect(self.object.get_absolute_url() + '/')

class AddSnippetView(CreateView):
    template_name = 'paste/paste.html'
    form_class = SnippetForm

    def get_form(self, form_class):
        form = form_class(**self.get_form_kwargs())

        if 'fork' in self.request.GET:
            slug = self.request.GET['fork']

            queryset = Snippet.objects.filter(slug=slug).exclude(expires__lte=datetime.datetime.now())

            try:
                object = queryset.get()
            except ObjectDoesNotExist:
                raise Http404('No snippet named {}'.format(slug))

            form.fields['content'].initial = object.content
            form.fields['parent'].initial = object

        lexer_name = get_lexer(self.request, ['fork'])
        if lexer_name:
            try:
                lexer = get_lexer_by_name(lexer_name)
            except:
                form.fields['lexer'].initial = lexer_name
                return form

            try:
                lexer_name = lexer.aliases[0]
            except:
                pass

            form.fields['lexer'].initial = lexer_name

            for l in form.fields['lexer'].choices:
                if lexer_name == l[0]:
                    return form

            form.fields['lexer'].choices.insert(0, (lexer_name, lexer.name))

        return form

    def form_valid(self, form):
        obj = form.save(commit=False)
        if self.request.user.is_authenticated():
            obj.author = self.request.user
        obj.save()

        if form.cleaned_data.get('lexer') == 'g':
            return HttpResponseRedirect(obj.get_absolute_url() + '/')
        return HttpResponseRedirect(obj.get_absolute_url() + '?' + form.cleaned_data.get('lexer'))

class IndexView(AddSnippetView):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        author = None

        if 'api' in request.GET:
            try:
                author = Key.objects.get(key=request.GET['api']).user
            except ObjectDoesNotExist:
                pass

        if PASTE_KEY not in request.POST:
            return HttpResponse('')

        snippet = Snippet(content=request.POST[PASTE_KEY], author=author)
        snippet.save()

        if 'HTTP_HOST' in request.META:
            return HttpResponse('http://%s/%s\n' % (request.META['HTTP_HOST'], snippet.slug))

        site = Site.objects.get_current()

        return HttpResponse('http://%s/%s\n' % (site.domain, snippet.slug))


class SnippetView(DetailView):
    model = Snippet

    def get_context_data(self, **kwargs):
        context = super(SnippetView, self).get_context_data(**kwargs)
        context['content'] = self.content
        context['processed_content'] = self.get_processed_content()
        context['lexer'] = self.lexer_name
        context['fluid'] = True

        return context

    def get_object(self, slug_field='slug'):
        if slug_field not in self.kwargs:
            slug_field = 'a'
        queryset = self.get_queryset()
        queryset = queryset.filter(slug=self.kwargs.get(slug_field)).exclude(expires__lte=datetime.datetime.now())

        try:
            object = queryset.get()
        except ObjectDoesNotExist:
            raise Http404('No snippet named {}'.format(self.kwargs[slug_field]))

        return object

    def get_content(self):
        content = self.get_object().content

        if 'wrap' in self.request.GET:
            content = '\n'.join(['\n'.join(textwrap.wrap(line, 80)) for line in content.splitlines()])

        return content

    def get_processed_content(self):
        self.lexer_name = get_lexer(self.request, ['wrap'])

        m = VIM_MODELINE_RE.search(self.content)
        if m:
            modes = m.group(3)
            if ':' in modes:
                modes = modes.split(':')
            else:
                modes = modes.split(' ')

            pairs = {}
            for mode in modes:
                if '=' in mode:
                    k,v = mode.split('=')
                    pairs[k] = v
                else:
                    pairs[mode] = None

            if 'syntax' in pairs and (not self.lexer_name or
                    self.lexer_name in ('g', 'guess')):
                self.lexer_name = pairs['syntax']

        if Markdown and self.lexer_name in ('markdown', 'md'):
            return mark_safe(Markdown(safe_mode=True, extensions=('codehilite',)).convert(self.content))

        if publish_parts and self.lexer_name == 'rrst':
            parts = publish_parts(source=self.content, writer_name="html4css1")
            return mark_safe(parts["fragment"])

        try:
            if self.lexer_name in ('g', 'guess'):
                lexer = guess_lexer(self.content)
                self.lexer_name = lexer.name
            elif self.lexer_name:
                lexer = get_lexer_by_name(self.lexer_name)
            else:
                raise Exception
        except:
            try:
                lexer = guess_lexer(self.content)
            except:
                lexer = PythonLexer()

        try:
            return mark_safe(highlight(self.content,  lexer,
                HtmlFormatter(linenos='table', cssclass='table',
                    anchorlinenos=True, lineanchors='l')))
        except:
            return escape(self.content)

    def get(self, request, *args, **kwargs):
        self.content = self.get_content()

        if len(self.request.GET) or request.path.endswith('/'):
            return super(SnippetView, self).get(request, *args, **kwargs)

        return HttpResponse(self.content, content_type='text/plain; charset=UTF-8')


class DiffMixin(object):
    def get_context_data(self, **kwargs):
        context = super(DiffMixin, self).get_context_data(**kwargs)
        context['a'] = self.a
        context['b'] = self.b
        return context

    def get_content(self):
        self.a = self.get_object('a')
        self.b = self.get_object('b')

        if self.a.content == self.b.content:
            return '{} and {} are the same.'.format(self.a, self.b)

        d = difflib.unified_diff(self.a.content.splitlines(), self.b.content.splitlines(), self.a.slug, self.b.slug, lineterm='')

        return '\n'.join(d)


class DiffView(DiffMixin, SnippetView):
    pass

paste/templates/paste/paste.html
{% extends "base.html" %}

{% block head %}paste{% endblock %}

{% block title %}New Snippet{% endblock %}

{% block content %}
    <h2>New Snippet</h2>

    <form class="form-horizontal" action="/paste/" method="post">{% csrf_token %}
        <fieldset>
          {% for field in form %}
            {% if not field.is_hidden %}
                <div class="control-group{% if field.errors %} error{% endif %}">
                    <label for="{{ field.auto_id }}" class="control-label">
                        {{ field.label|safe }}
                    </label>
                    <div class="controls">
                        {{ field }}
                      {% if field.help_text %}
                        <p class="help-block">{{ field.help_text }}</p>
                      {% endif %}
                    </div>
                </div>
            {% else %}
                {{ field }}
            {% endif %}
          {% endfor %}

            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Share</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" charset="utf-8">
        lexers = document.getElementById("id_lexer");
        lexers.onchange = function() {
            if (this.value=='more') {
                location.href='/syntax/';
            }
        }

        none = document.createElement("OPTION");
        none.text = "--";
        none.value = "";
        lexers.options.add(none);

        more = document.createElement("OPTION");
        more.text = "More";
        more.value = "more";
        lexers.options.add(more);
    </script>
{% endblock %}

{% block sidebar_extra %}
    <h3>Why use snippt?</h3>
    <ul>
        <li><a href="/syntax/" title="List of supported syntax">Supports over 200 different syntax</a></li>
        <li>Render markdown and restructured text</li>
        <li>User accounts</li>
        <li><a href="/man" title="manpage for snippt">CLI pasting</a></li>
    </ul>

  {% if user.is_authenticated %}
    <h3>Recent Snippets</h3>
    <ul>
      {% for paste in user.snippet_set.recent %}
        <li><a href="{{ paste.get_absolute_url }}/">{{ paste }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

paste/templates/paste/paste_detail.html
{% extends "base.html" %}

{% block content %}
    {{ processed_content }}
{% endblock %}

{% block sidebar %}
    <h3>Snippet {{ object }}</h3>

    <ul>
      {% if object.author %}
        <li>By {{ object.author }}</li>
      {% endif %}

      {% if object.published %}
        <li>Published: {{ object.published }}</li>
      {% endif %}

      {% if object.expires %}
        <li>Expires: {{ object.expires }}</li>
      {% endif %}
    </ul>

    <h3>View Options</h3>

    <ul>
        <li><a href="/{{ object.slug }}">Raw</a></li>

      {% ifequal lexer "rrst" %}
        <li><a href="/{{ object.slug }}?rst">RST Syntax</a></li>
      {% endifequal %}

      {% ifequal lexer "rst" %}
        <li><a href="/{{ object.slug }}?rrst">Render RST</a></li>
      {% endifequal %}
    </ul>

    {% if a %}
        <h3>Diff</h3>

        <ul>
            <li><a href="{{ a.get_absolute_url }}?g">{{ a }}</a></li>
            <li><a href="{{ b.get_absolute_url }}?g">{{ b }}</a></li>
        </ul>
    {% endif %}
{% endblock %}

paste/templates/paste/snippet_detail.html
{% extends "base.html" %}

{% block title %}Snippet {{ object }}{% endblock %}

{% block nav_class %}container-fluid{% endblock %}

{% block wrapper %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span8">
                <h1>
                    {{ object }}
                  {% if object.author %}
                    {% load gravatar %}
                    <small><a href="/u/{{ object.author }}/">
                        <img width="20" heigt="20" src="{% gravatar object.author.email 20 %}"
                            class="avatar" />
                        {{ object.author }}
                    </a></small>
                  {% endif %}
                </h1>
            </div>

            <div class="span4">
                <div class="btn-group pull-right">
                    <a href="/?fork={{ object.slug }}" class="btn">Fork</a>
                    <a href="{{ object.get_absolute_url }}" class="btn">Raw</a>
                    <a href="#share" data-toggle="modal" class="btn">Share</a>
                  {% ifequal object.author user %}
                    <a href="#confirm-delete" data-toggle="modal" class="btn btn-danger">Delete</a>
                  {% endifequal %}
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div id="paste">
                {{ processed_content }}
            </div>
        </div>
    </div>

  {% ifequal object.author user %}
    <div class="modal fade" id="confirm-delete">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Delete {{ object }}</h3>
        </div>

        <div class="modal-body">
            <p>Confirm delete</p>
        </div>

        <div class="modal-footer">
            <form action="{{ object.get_absolute_url }}/delete/" method="post" accept-charset="utf-8">
                <a href="#" class="btn" data-dismiss="modal">Close</a>

                {% csrf_token %}
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
    </div>
  {% endifequal %}
</div>
{% endblock %}

paste/templates/paste/syntax_list.html
{% extends "base.html" %}

{% block head %}paste{% endblock %}

{% block title %}List of supported syntax{% endblock %}

{% block content %}
    <h1>Supported Syntax</h1>
    <ul>
      {% for syntax in syntax_list %}
        <li><a href="/?{{ syntax.0 }}" title="Create a snippet with {{ syntax.1 }}">{{ syntax.1 }}</a></li>
      {% endfor %}
    </ul>
{% endblock %}

paste/templates/paste/user_detail.html
{% extends "base.html" %}

{% block head %}paste{% endblock %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
    <h1>Public snippet for {{ object }}</h1>

    <ul>
      {% for snippet in object.snippet_set.public %}
        <li><a href="{{ snippet.get_absolute_url }}/">{{ snippet }}</a>{% if snippet.title %} ({{ snippet.title }}){% endif %}</li>
      {% endfor %}
    </ul>
{% endblock %}